spring:
  application:
    name: doc-provider


relaxed:
  vCode:
    image:
      enabled: true
      length: 4


server:
  port: 9091
springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
#springdoc:
#  swagger-ui:
#    # 修改Swagger UI路径
#    path: /swagger-ui.html
#    # 开启Swagger UI界面
#    enabled: true
#  api-docs:
#    # 修改api-docs路径
#    path: /v3/api-docs
#    # 开启api-docs
#    enabled: true
#  # 配置需要生成接口文档的扫描包
#  packages-to-scan: com.macro.mall.tiny.controller
#  # 配置需要生成接口文档的接口路径
#  paths-to-match: /brand/**,/admin/**
logging:
  level:
    root: debug
