spring:
  mail:
    host: smtp.163.com
    port: 25
    username: username@163.com
    password: 123456
    default-encoding: UTF-8
    properties:
      from: from@163.com
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

relaxed:
  dingtalk:
    url: https://oapi.dingtalk.com/robot/send?access_token=b7152491511299a498d5887daf99fbc5b6c5dc5a1a721458752580a9626c7f979
    secret: SEC87dcc5c1d2b8a1d94a9cf81a67775aa8578987594a891bf51ce46fb4cf05a119
  sftp:
    host: 127.0.0.1
    port: 22
    username: root
    password: 123456
    sessionConnectTimeout: 15000
    channelConnectedTimeout: 15000
    pool:
      max-total: 20
      max-idle: 10
      min-idle: 5
      lifo: true
      fairness: false
      max-wait-millis: 5000
      min-evictable-idle-time-millis: -1
      evictor-shutdown-timeout-millis: 10000
      soft-min-evictable-idle-time-millis: 1800000
      num-tests-per-eviction-run: 3
      test-on-create: false
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 600000
      block-when-exhausted: true
      jmx-enabled: false
      jmx-name-prefix: pool
      jmx-name-base: sftp
    abandoned:
      remove-abandoned-on-borrow: true
      remove-abandoned-on-maintenance: true
      remove-abandoned-timeout: 300
      log-abandoned: false
      require-full-stack-trace: false
      use-usage-tracking: false
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9190/xxl-job-admin
    executor:
      appname: xxl-executor-name
      ip: 192.168.0.102
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /data/applogs/xxl-job/jobhandler
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30

