spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8081


relaxed:
  swagger:
    title: Show Docs
    group-name: 风控服务
    documentation-type: swagger_2
    description:  风控接口服务Api文档
    version: 0.0.1
    license: Powered By Test
    licenseUrl: http://www.test.cn/
    terms-of-service-url: http://www.test.cn/
    host: localhost:8081
    contact:
      name: test
      email: test@foxmail.com
      url: https://github.com/test
    provider:
      aggregator-origin: http://test-admin:8080
