spring:
  datasource:
    username: root
    password: '123456'
    url: jdbc:mysql://127.0.0.1:3306/multi-datasource?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    queryDsSql:  SELECT * FROM `t_data_source`


jasypt:
  encryptor:
    password: "123456"